#!/usr/bin/env python
# -*- coding: utf-8 -*-

from enum import Enum, auto

class ArtemisEvent(Enum):
    """ Enum values for events """
    NONE = 0
    ALL_FIGHTERS_DOCKED = auto()
    ALWAYS_ON = auto()
    ANY_FIGHTER_READY = auto()
    ANY_TUBE_EMPTY = auto()
    ANY_TUBE_READY_TO_FIRE = auto()
    AUTO_BEAMS_ON = auto()
    BEAMS_EXIST = auto()
    COMPLETELY_DOCKED = auto()
    FIGHTER_BAY_EXISTS = auto()
    FIGHTER_BAY0_READY_SHUTTLE = auto()
    FIGHTER_BAY1_EXISTS = auto()
    FIGHTER_BAY1_READY_FIGHTER = auto()
    FIGHTER_BAY2_EXISTS = auto()
    FIGHTER_BAY2_READY_FIGHTER = auto()
    FIGHTER_BAY2_REFITTING_FIGHTER = auto()
    FIGHTER_BAY3_EXISTS = auto()
    FIGHTER_BAY3_READY_FIGHTER = auto()
    FIGHTER_BAY4_EXISTS = auto()
    FIGHTER_BAY4_READY_FIGHTER = auto()
    FIGHTER_BAY5_EXISTS = auto()
    FIGHTER_BAY5_READY_FIGHTER = auto()
    FIGHTER_BOOSTING = auto()
    FIGHTER_BRAKING = auto()
    FIGHTER_DOCKED = auto()
    FIGHTER_LAUNCHED = auto()
    FRONT_SHIELD_100 = auto()
    FRONT_SHIELD_20 = auto()
    FRONT_SHIELD_40 = auto()
    FRONT_SHIELD_60 = auto()
    FRONT_SHIELD_80 = auto()
    FRONT_SHIELD_LOW = auto()
    HULL_INTEGRITY_100 = auto()
    HULL_INTEGRITY_40 = auto()
    HULL_INTEGRITY_60 = auto()
    HULL_INTEGRITY_80 = auto()
    INCOMING_COMMUNICATION_ALERT = auto()
    INCOMING_COMMUNICATION_ENEMY = auto()
    INCOMING_COMMUNICATION_STATION = auto()
    MAIN_SCREEN_FORE_VIEW = auto()
    NORMAL_CONDITION_1 = auto()
    PLAYER_DESTROYED = auto()
    PLAYER_SHIELDS_ON = auto()
    PLAYER_TAKES_FRONT_SHIELD_DAMAGE = auto()
    PLAYER_TAKES_SHIELD_DAMAGE = auto()
    SOMETHING_HITS_PLAYER = auto()
    TUBE1_EMPTY = auto()
    TUBE1_EXISTS = auto()
    TUBE1_READY_TO_FIRE_HOMING = auto()


ALL_FIGHTERS_DOCKED = "ALL_FIGHTERS_DOCKED"
ALWAYS_ON = "ALWAYS_ON"
ANY_FIGHTER_READY = "ANY_FIGHTER_READY"
ANY_TUBE_EMPTY = "ANY_TUBE_EMPTY"
ANY_TUBE_READY_TO_FIRE = "ANY_TUBE_READY_TO_FIRE"
AUTO_BEAMS_ON = "AUTO_BEAMS_ON"
BEAMS_EXIST = "BEAMS_EXIST"
COMPLETELY_DOCKED = "COMPLETELY_DOCKED"
FIGHTER_BAY_EXISTS = "FIGHTER_BAY_EXISTS"
FIGHTER_BAY0_READY_SHUTTLE = "FIGHTER_BAY0_READY_SHUTTLE"
FIGHTER_BAY1_EXISTS = "FIGHTER_BAY1_EXISTS"
FIGHTER_BAY1_READY_FIGHTER = "FIGHTER_BAY1_READY_FIGHTER"
FIGHTER_BAY2_EXISTS = "FIGHTER_BAY2_EXISTS"
FIGHTER_BAY2_READY_FIGHTER = "FIGHTER_BAY2_READY_FIGHTER"
FIGHTER_BAY2_REFITTING_FIGHTER = "FIGHTER_BAY2_REFITTING_FIGHTER"
FIGHTER_BAY3_EXISTS = "FIGHTER_BAY3_EXISTS"
FIGHTER_BAY3_READY_FIGHTER = "FIGHTER_BAY3_READY_FIGHTER"
FIGHTER_BAY4_EXISTS = "FIGHTER_BAY4_EXISTS"
FIGHTER_BAY4_READY_FIGHTER = "FIGHTER_BAY4_READY_FIGHTER"
FIGHTER_BAY5_EXISTS = "FIGHTER_BAY5_EXISTS"
FIGHTER_BAY5_READY_FIGHTER = "FIGHTER_BAY5_READY_FIGHTER"
FIGHTER_BOOSTING = "FIGHTER_BOOSTING"
FIGHTER_BRAKING = "FIGHTER_BRAKING"
FIGHTER_DOCKED = "FIGHTER_DOCKED"
FIGHTER_LAUNCHED = "FIGHTER_LAUNCHED"
FRONT_SHIELD_100 = "FRONT_SHIELD_100"
FRONT_SHIELD_20 = "FRONT_SHIELD_20"
FRONT_SHIELD_40 = "FRONT_SHIELD_40"
FRONT_SHIELD_60 = "FRONT_SHIELD_60"
FRONT_SHIELD_80 = "FRONT_SHIELD_80"
FRONT_SHIELD_LOW = "FRONT_SHIELD_LOW"
HULL_INTEGRITY_100 = "HULL_INTEGRITY_100"
HULL_INTEGRITY_40 = "HULL_INTEGRITY_40"
HULL_INTEGRITY_60 = "HULL_INTEGRITY_60"
HULL_INTEGRITY_80 = "HULL_INTEGRITY_80"
INCOMING_COMMUNICATION_ALERT = "INCOMING_COMMUNICATION_ALERT"
INCOMING_COMMUNICATION_ENEMY = "INCOMING_COMMUNICATION_ENEMY"
INCOMING_COMMUNICATION_STATION = "INCOMING_COMMUNICATION_STATION"
MAIN_SCREEN_FORE_VIEW = "MAIN_SCREEN_FORE_VIEW"
NORMAL_CONDITION_1 = "NORMAL_CONDITION_1"
PLAYER_DESTROYED = "PLAYER_DESTROYED"
PLAYER_SHIELDS_ON = "PLAYER_SHIELDS_ON"
PLAYER_TAKES_FRONT_SHIELD_DAMAGE = "PLAYER_TAKES_FRONT_SHIELD_DAMAGE"
PLAYER_TAKES_SHIELD_DAMAGE = "PLAYER_TAKES_SHIELD_DAMAGE"
SOMETHING_HITS_PLAYER = "SOMETHING_HITS_PLAYER"
TUBE1_EMPTY = "TUBE1_EMPTY"
TUBE1_EXISTS = "TUBE1_EXISTS"
TUBE1_READY_TO_FIRE_HOMING = "TUBE1_READY_TO_FIRE_HOMING"

FRONT_SHIELD_ = "FRONT_SHIELD_"


SILENCED_EVENTS = [
    PLAYER_TAKES_FRONT_SHIELD_DAMAGE,
    PLAYER_TAKES_SHIELD_DAMAGE,
    SOMETHING_HITS_PLAYER,
]